### ISSUE TITLE
text field  Some characters are missing.

### ISSUE THREAD

**Issue by ocoderr** [bisguzar/twitter-scraper#102]
testuser: NoDaysOffCrypto
my code 
`
from twitter_scraper import get_tweets

for tweet in get_tweets('NoDaysOffCrypto', pages=1):
    if tweet['tweetId'] == '1209138991347326976':
        print(tweet)
`
output . 
{'tweetId': '1209138991347326976', 'isRetweet': False, 'time': datetime.datetime(2019, 12, 23, 23, 49, 34), 'text': 'The best #Cryptoassets wallet in the #cryptocurrencymarket to store your #Cryptocurrency with upgraded Security Protocols\nManage your #BTC, #ETH #XRP #TRX #XRP #DOGE with Huobi Wallet App\nHows that for a post? Lol  @HuobiWallet \nFor Doge: **D6eSXqBiJutuUP55eXWn6ceB5DG6QS4q9** https://twitter.com/HuobiWallet/status/1204645286863200256\xa0…', 'replies': 5, 'retweets': 14, 'likes': 37, 'entries': {'hashtags': ['#Cryptoassets', '#cryptocurrencymarket', '#Cryptocurrency', '#BTC', '#ETH', '#XRP', '#TRX', '#XRP', '#DOGE', '#BTC', '#ETH', '#XRP', '#TRX', '#XRP', '#DOGE'], 'urls': [], 'photos': [], 'videos': []}}

full text https://twitter.com/NoDaysOffCrypto/status/1209138991347326976

**D6eSXqBiJutuUP55eXWn6ceB5DG6QS4q9**  missing the last **x**

**Comment by bisguzar** [comment]
Hi @ocoderr thanks for your reporting and suggestion. Please review my PR (#104) and comment your reviews. So I can merge it and close this issue.

**Comment by emregeldegul** [comment]
I think this issue is solved

**Comment by bisguzar** [comment]
Thanks for your review @emregeldegul . Merged
