### ISSUE TITLE
Expose the internal `gen_tweets()`

### ISSUE THREAD

**Issue by mindflayer** [bisguzar/twitter-scraper#117]
As you commented in the source code, the same function can be also used `# for searching:`.
Please expose the internal `gen_tweets()` in case someone would like to use it directly.

In case you like the idea but have no time for that, I am able to contribute to it since I am doing this for my company.

P.S.: I see the module `tweets` is importing `mechanicalsoup` without using it.

**Comment by bisguzar** [comment]
Hi! Thanks for your attention, but I couldn't understand that, why you want to use gen_tweets() directly?

**Comment by mindflayer** [comment]
Because 

> Hi! Thanks for your attention, but I couldn't understand that, why you want to use gen_tweets() directly?
Because I want to specify a different URL, but there's more I could do.

**Comment by bisguzar** [comment]
To be honest, I couldn't understand it all. What kind of URL you are talking about? Can you talk more spesific?

**Comment by mindflayer** [comment]
Well, it's about applying good software engineering principles.
You've done something which people can use in different ways, but if you put a function inside another that's not exposing anything useful if not for people with your exact use-case.
At the end I ended up rewriting what I needed, but I recommend you refactor your code in a way that could help more people. It's just my 2 cents because I found it useful but not in the form you ship it.

**Comment by bisguzar** [comment]
Thanks for your suggestions, but twitter-scraper is a simply non-auth required api. It must be simple. As you can see it licensed with MIT. So everyone can change the source for their requirements.

If you have a feature idea, please open a new issue or create PR directly. I will merge it pleasurely.
