### ISSUE TITLE
Following-Follower Count Is Wrong (Swapped)

### ISSUE THREAD

**Issue by DenizDalkilic10** [bisguzar/twitter-scraper#119]
I am fetching the account information from 10 different sources and only one of the accounts show wrong information about the number followers and followings. The numbers are provided in swapped form. I have tried with different number of sources but there is one specific source giving wrong information "Breaking911". The account has 0 followings and 570k followers but these numbers are displayed as 1 follower and 570k followings. I believe there could be a bug due to having accounts with 0 "followings"

**Comment by DenizDalkilic10** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/28291035/79893212-665bfd00-840c-11ea-8ff9-5f8afc15c149.PNG)

**Comment by DenizDalkilic10** [comment]
[UPDATE] In reality the account "Breaking911" has 0 followings and 527k followers

**Comment by bisguzar** [comment]
Hi, thanks for the issue. Please checkout #120 and test it. Don't forget to leave a message. Then I can merge it pleasurely.
