### ISSUE TITLE
Specialized Links can not be fetched

### ISSUE THREAD

**Issue by DenizDalkilic10** [bisguzar/twitter-scraper#122]
Some accounts use special links which are displayed as buttons with images, and in the entries obtained from calling get_tweets(), these links can not be seen in the field of "urls". The specialized link that I am talking about can be seen in the image below. It is not explicitly displayed but rather wrapped in an image button.
![tweet](https://user-images.githubusercontent.com/28291035/80287024-bce07880-8737-11ea-957d-6b9dd9f9a491.PNG)

**Comment by bisguzar** [comment]
Hi, please take a look to #124 .
