### ISSUE TITLE
Can not fetch Retweeted Tweet content created with "Retweet with a Comment" option

### ISSUE THREAD

**Issue by DenizDalkilic10** [bisguzar/twitter-scraper#127]
Some tweets are retweeted by users using the "Retweet With Comment" option, and we need to access the text present in the retweeted tweet. The example for the mentioned tweets given as a screenshot below. It is not a regular retweet and it has its own unique tweet ID etc. Can you add a new field for tweets to retrieve these texts if they are present?

![Ekran Alıntısı](https://user-images.githubusercontent.com/28291035/81013329-a20eb200-8e63-11ea-8fc1-c80c55a7dea9.PNG)

**Comment by bisguzar** [comment]
*url* field also contains original tweet's url. Might be it be usefull. I'm dont have an plan to add this feature soon. If you create PR, I can merge it.
