### ISSUE TITLE
Check profile is verified.

### ISSUE THREAD

**Issue by ozanbayram** [bisguzar/twitter-scraper#128]
I am interested in adding new attribute in class Profile. It shows whether profile is verified. Also I checked what kind of exception raising if no location. It returns anything and should be 'None' . In addition location hasn't added to dict yet.

**Comment by ozanbayram** [comment]
I look forward to hearing from you. If you like it, I will create pull request.

**Comment by bisguzar** [comment]
Sounds awesome, please go ahead!
