### ISSUE TITLE
Twitter is removing the Old UI, will this affect twitter-scraper?

### ISSUE THREAD

**Issue by IamRifki** [bisguzar/twitter-scraper#132]
Here's the notice that they gave, I also noted that there were references to old twitter UI elements in the code.

![](https://user-images.githubusercontent.com/39834015/81482763-97895980-9263-11ea-97d7-0330cc358279.png)

**Comment by bisguzar** [comment]
It will effect Profile class ninety percent but I'm not sure about get_tweets function. We will see and re-optimize together.
