### ISSUE TITLE
I cannot check if a tweet is pinned or not.

### ISSUE THREAD

**Issue by Flumbo123** [bisguzar/twitter-scraper#134]
Is there any way to check if a tweet is pinned or not? I see there is a "isRetweet" attribute that returns a boolean, I'd love to see a "isPinned" attribute that returns a boolean as well!

**Comment by ozanbayram** [comment]
Maybe I can add this atrribute. I will try to work on it in my free time.

**Comment by bisguzar** [comment]
Glad to hear that @ozanbayram ! I'm waiting your PR excitedly.

**Comment by jcea** [comment]
Hitting this problem too.

**Comment by bisguzar** [comment]
Hi @ozanbayram , do you have any updates?

**Comment by ozanbayram** [comment]
Sorry, I guess in I can't

**Comment by bisguzar** [comment]
Please take a look to #138 and leave your reviews.
