### ISSUE TITLE
requests.exceptions.SSLError: HTTPSConnectionPool(host='twitter.com', port=443)

### ISSUE THREAD

**Issue by icmpnorequest** [bisguzar/twitter-scraper#135]
Hi team,

When scraping tweets, I met this issue. The code and error is as below:
```
from twitter_scraper import get_tweets

for tweet in get_tweets('realDonaldTrump', pages=5):
    print(tweet['text'])
```

Error:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='twitter.com', port=443): Max retries exceeded with url: /i/profiles/show/realDonaldTrump/timeline/tweets?include_available_features=1&include_entities=1&include_new_items_bar=true (Caused by SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')")))
```

Any ideas to solve?

**Comment by bisguzar** [comment]
It's look like a connection problem, please report is it still raising error?

**Comment by icmpnorequest** [comment]
Hi @bisguzar,

Yes, I still meet the same error. Any ideas to solve?

**Comment by bisguzar** [comment]
It's all about connection. Might be twitter blocking you if you are trying to scrape a lot in short term.

> server refuses your connection (you're sending too many requests from same ip address in short period of time) 
\- [djra (stakoverflow)](https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url-in-requests)

**Comment by icmpnorequest** [comment]
Hi @bisguzar,

I have tried to change IP address with IP proxy pool, but still doesn't work. Twitter uses browser fingerprinting to track users, I was wondering if the blocking of my connection is affected by the fingerprinting technique? 

Do you think should I try more IP address to solve the connection error problem? Thanks in advance for your response.

**Comment by bisguzar** [comment]
I'm not competent about twitter's algorithms honestly. It's hard to say sthg for me. What do you think changing user-agent headers and try on new device with new, clean connection?

**Comment by icmpnorequest** [comment]
Hi @bisguzar ,

Still having the ConnectionError. However, I could download the json data from the interface manually and parse tweets from it. When using `Requests`, it failed. Maybe Twitter could detect requests created by `Requests`.

**Comment by icmpnorequest** [comment]
Finally fixed this issue by changing to another proxy. The 443 connection error happened for the usage of my Shadowsocks server.

**Comment by bisguzar** [comment]
I'm happy to hear that!

**Comment by h4m5t** [comment]
> Finally fixed this issue by changing to another proxy. The 443 connection error happened for the usage of my Shadowsocks server.

Can you tell me how did you solve it?  thanks!
