### ISSUE TITLE
Always retrying as the program is running

### ISSUE THREAD

**Issue by zhicheng0501** [bisguzar/twitter-scraper#142]
Hi, as i run the program on my mac, it always showing retrying.
At the beginning i thought it would be the proxy's problem. I tried to change another proxy website and the same problem occurred.
Does anyone know what is the real problem?
![屏幕快照 2020-06-05 08 59 45](https://user-images.githubusercontent.com/48405087/83825120-021aa180-a70b-11ea-9475-d01ab6b3b898.png)

**Comment by bisguzar** [comment]
I think its not **twitter-scraper** if you didnt create logger for yourself.

**Comment by zhicheng0501** [comment]
> I think its not **twitter-scraper** if you didnt create logger for yourself.

thanks for reminding me.
