### ISSUE TITLE
Error name 'breakpoint' is not defined (Profile)?

### ISSUE THREAD

**Issue by MaximAbdulatif** [bisguzar/twitter-scraper#162]
Why am I getting this error ? 

Thanks in advance 

![Screenshot 2020-07-25 at 12 49 09](https://user-images.githubusercontent.com/20270945/88455442-a00e2b00-ce75-11ea-8189-0e33eae51de9.jpg)

**Comment by bisguzar** [comment]
You are getting error because of me. Might be related to #157 . Which version you are using? Can you upgrade the package version?

PS: Don't push new version if you are sleepy

**Comment by MaximAbdulatif** [comment]
Brilliant ! Upgraded the package and its working fine, many thanks 

![Screenshot 2020-07-27 at 17 59 34](https://user-images.githubusercontent.com/20270945/88564247-46535f80-d033-11ea-814a-867278eea4d2.jpg)

**Comment by bisguzar** [comment]
Great, have fun with the library^^
