### ISSUE TITLE
Looks like twitter has broken this api. Here is a little work around.

### ISSUE THREAD

**Issue by dgnsrekt** [bisguzar/twitter-scraper#170]
If you were relying on this api. Here is a quick work around I put together today using nitter.
https://github.com/dgnsrekt/nitter_scraper
I've got a decent portion of the profile and tweet parser running.

**Comment by bisguzar** [comment]
Its not how open-source works. You are free to create new solutions. But if you want to improve something, just commit into it. If you want to create new things, just create. But if you share this here, its a kind of advertisement IMO.

Again, you are free to commit into this project.
