### ISSUE TITLE
Documentation: Addressing shadow-bans

### ISSUE THREAD

**Issue by BrandonKMLee** [bisguzar/twitter-scraper#187]
Observing https://github.com/twintproject/twint/blob/master/README.md#faq does this repo support Shadow-Banned users?

**Comment by bisguzar** [comment]
No, twitter-scraper doesn't have any options to handle/parse shadow-banned accounts.

**Comment by BrandonKMLee** [comment]
Thanks for the reply. Hope that this can be documented.

**Comment by bisguzar** [comment]
We need to fix our critical bugs first. Maybe twitter-scraper can support this in future. Feel free to opening new issues for your questions, I'm closing this one.
