### ISSUE TITLE
Only Scrape the First tweet

### ISSUE THREAD

**Issue by THOOSJE2005** [bisguzar/twitter-scraper#65]
Hello,

is it possible to only scrape the first tweet of a profile? (Not pinned/retweeted). This would make my program faster. It would also be nice if there is an option to see who is tagged in the tweet.

Thanks for your time,
Thoosje

**Comment by bisguzar** [comment]
What about using **pages** parameter for get_tweets method? It'll load few tweets from beginning. There is no option to get first tweet only.

**Comment by THOOSJE2005** [comment]
Thx for the fast response. I already only scrape the first page but I really need the first tweet. Not page

**Comment by bisguzar** [comment]
get_tweets is a generator, you can break loop after recieve first tweet. Its not best practicle and speed still depends on your connection speed, FYI. Here is my basic benchmark results

```
Elapsed time (all_tweets_on_firstpage): 1.648399829864502
Elapsed time (break_after_first_tweet): 0.9781053066253662
```

```python
from twitter_scraper import get_tweets

from functools import wraps
from time import time


def timing(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        start = time()
        result = f(*args, **kwargs)
        end = time()
        print (f'Elapsed time ({f.__name__}): {end-start}')
        return result
    return wrapper


@timing
def all_tweets_on_firstpage():
    for tweet in get_tweets('bugraisguzar', pages=1):
        pass

@timing
def break_after_first_tweet():
    for tweet in get_tweets('bugraisguzar', pages=1):
        break


if __name__=="__main__":
    all_tweets_on_firstpage()
    break_after_first_tweet()

```

**Comment by THOOSJE2005** [comment]
Thx! Is it also possible to detect if someone is tagged?

**Comment by bisguzar** [comment]
You can parse text of tweet to detect tags and hastags in it. If anyone insterest, please send a PR ans return these fields too.
