### ISSUE TITLE
Need some help running the virtualenv on Windows.

### ISSUE THREAD

**Issue by silvererudite** [bisguzar/twitter-scraper#76]
I set up pipenv and was trying with first approach using Markov. I could do till installing Markovify. But then how to run the virtualenv and start typing commands?  If I type pipenv run/shell after installing, I still don't get how to get to the interpreter option to type python commands
![Screenshot (19)](https://user-images.githubusercontent.com/24827548/64326794-65e13400-cfec-11e9-8062-5188c92cd33b.png) 
this is what I get when I navigate to the directory but as you can see there is a number of actvate files. When I go on to run any of them the terminal opens and disappears.
I'm running python 3.7+ on Windows 10.

**Comment by bisguzar** [comment]
Just go into virtualenv with **pipenv shell** and run python inside it. Or use **pipenv run x.py** to run X.py inside VIRTUALENV

**Comment by silvererudite** [comment]
thank you :)
