### ISSUE TITLE
Deprecated PyPi version

### ISSUE THREAD

**Issue by NJannasch** [bisguzar/twitter-scraper#81]
Thanks for you nice work.

It would be nice if you could provide a new release so that the PyPI package gets upgraded as well.

Best regards

**Comment by bisguzar** [comment]
Thank you for your interest. It's actually @kennethreitz 's project. I don't have permissions on PyPI. I'm working on it, I will close this issue when I figured it out.

**Comment by kennethreitz** [comment]
@bisguzar what's your pypi username?

**Comment by bisguzar** [comment]
Same with my github username but I recieved an email about permissions. Thanks @kennethreitz , I will push new versions as soon as possible.
