### ISSUE TITLE
Does anybody knows why it dosen't work?

### ISSUE THREAD

**Issue by CptTH** [bisguzar/twitter-scraper#87]
I cannot do anything.
I download python3, and installed packages.. but It doesn't work.

Does anybody knows why it happened?

![오류](https://user-images.githubusercontent.com/49192149/69372002-3df89700-0ce4-11ea-9ffc-2510adf963ee.JPG)

**Comment by bisguzar** [comment]
If you installed from PyPI, can you install from repository and try again? Because the library on PyPI is deprecated.

**Comment by CptTH** [comment]
I did it, but still doesn't work.

Error message : No module named 'setuptools'.
Is that anything that I missed?

![오류2](https://user-images.githubusercontent.com/49192149/69373961-64b8cc80-0ce8-11ea-829f-2fac26b0274e.JPG)

**Comment by MasterOfTheTiger** [comment]
Install setuptools. That's all you need here.

**Comment by CptTH** [comment]
I finally did it! But, It has just one problem ( bug ) left. I'll issue new one for it!

Thanks 
@bisguzar @MasterOfTheTiger

**Comment by CptTH** [comment]
@bisguzar 
I issued bug report and PR fixed version of source code.
please check it!

related #88 #89
