### ISSUE TITLE
cannot get all the tweets from a certain username

### ISSUE THREAD

**Issue by liyunrui** [bisguzar/twitter-scraper#96]

**Comment by bisguzar** [comment]
Can you share which username you tested on?

**Comment by liyunrui** [comment]
username: realDonaldTrump

**Problem Issue:**
I set pages = 50,000, try to get all tweets from him, but the problem I encountered is like the numbers of the post we scraped is different and scale of range varies a lot. For example, I got the number surrounding 800~1500 tweets. (But his page shows he has 47,000 tweets)

**Question**
Could you give me some clue why ? Or what's parameter I can set to get all the tweets from a certain user?

**Comment by FelipeLema** [comment]
I used `pages=float('int')` instead for a different user (JulioVidela1), also getting arround 800 tweets (it reports +16_000)

**Comment by reneroth** [comment]
I'm having a similar issue, with fetching all tweets from a user always stopping way before what I know the true end of the timeline to be. But scrolling down all the way in-browser makes me hit the Twitter rate limit too, so maybe it's the same problem? I was sort of half-expecting this library to throttle itself to keep up with rate limits. Are there different libraries out there that'll allow me to truly dump a whole Twitter profile with minimal user intervention?

**Comment by bisguzar** [comment]
To be honest, I don't know why its happening. Might be twitter detecting an automated action and blocking it. I will research it as soon as possible.

**Comment by BenMMcLean** [comment]
I get the same issue. Playing around with the code a bit, it throws a ParserError with the message "Document is empty"

**Comment by reneroth** [comment]
Adding to my previous observation, while you cannot get all Tweets directly from a user's profile after a certain threshold, you can use the search function to overcome that limit:
https://twitter.com/search?q=from%3Ajack&src=typed_query&f=live

**Comment by bisguzar** [comment]
Look like its not possible to get all tweets. Because twitter limits scrolling ([twint](https://github.com/twintproject/twint)'s authors says).
