### ISSUE TITLE
Comparison/Compatibility between this and Twint

### ISSUE THREAD

**Issue by DonaldTsang** [bisguzar/twitter-scraper#97]
What are the basic differences between this repo and Twint's API-free scraping?

**Comment by DonaldTsang** [comment]
https://github.com/taspinar/twitterscraper/issues/248

**Comment by bisguzar** [comment]
According to my observations *twitterscraper* using beautifulsoup for scraping. **Twitter-scraper** (this repo) is using requests-html instead of bs4. And *twitterscraper* is more complex than this repo, this one is simplier

**Comment by DonaldTsang** [comment]
@bisguzar also any comments on https://github.com/twintproject/twint ?

**Comment by bisguzar** [comment]
**Twint** using bs4 too. But I don't know more :(

**Comment by DonaldTsang** [comment]
Might be a good idea to construct a features table between the repos so people can choose them with ease.

**Comment by bisguzar** [comment]
@DonaldTsang if you create an article about it I would gladly add a link to readme for this. Please feel free to contact me on twitter @bugraisguzar, or telegram (same as my github username).
